-- Enable pgvector extension
create extension if not exists vector;

-- Custom types and enums
create type processing_status as enum ('pending', 'extracting', 'chunking', 'embedding', 'analyzing', 'ready', 'failed');
create type question_type as enum ('multiple_choice', 'true_false', 'development');
create type cognitive_level as enum ('locate', 'interpret', 'reflect');
create type entity_type as enum ('character', 'event', 'space', 'conflict', 'theme');

-- Tables

-- 1. Profiles (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  full_name text,
  school_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Books
create table books (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  title text not null,
  author text,
  file_path text not null, -- path in storage bucket
  file_size_bytes bigint,
  page_count integer,
  processing_status processing_status default 'pending',
  processing_progress integer default 0, -- 0 to 100
  processing_error text,
  raw_text text, -- Optional, could be very large
  summary text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Book Chunks (for vector search)
create table book_chunks (
  id uuid default gen_random_uuid() primary key,
  book_id uuid references books(id) on delete cascade not null,
  chunk_index integer not null,
  content text not null,
  embedding vector(768), -- Gemini text-embedding-004 size
  page_number integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Book Entities (Characters, Spaces, Events, etc)
create table book_entities (
  id uuid default gen_random_uuid() primary key,
  book_id uuid references books(id) on delete cascade not null,
  entity_type entity_type not null,
  name text not null,
  description text not null,
  metadata jsonb, -- e.g., role, traits, relationships
  importance_score integer, -- 1-10
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Book Themes
create table book_themes (
  id uuid default gen_random_uuid() primary key,
  book_id uuid references books(id) on delete cascade not null,
  theme_name text not null,
  description text not null,
  evidence jsonb, -- array of chunk IDs or text references
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Question Bank (generated by AI)
create table question_bank (
  id uuid default gen_random_uuid() primary key,
  book_id uuid references books(id) on delete cascade not null,
  q_type question_type not null,
  cognitive_level cognitive_level not null,
  question_text text not null,
  correct_answer text not null,
  distractors jsonb, -- array of options for multiple choice
  rubric text, -- for development questions
  justification text, -- why is this the correct answer
  target_age integer, -- recommended minimum age
  traceability_chunks jsonb, -- array of book_chunks.id
  status text default 'draft', -- draft, reviewed, rejected
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Tests (instantiated evaluations)
create table tests (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  book_id uuid references books(id) on delete cascade not null,
  title text not null,
  target_grade text,
  instructions text,
  total_score integer,
  status text default 'draft', -- draft, published
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 8. Test Items (junction table tests <-> question_bank)
create table test_items (
  id uuid default gen_random_uuid() primary key,
  test_id uuid references tests(id) on delete cascade not null,
  question_id uuid references question_bank(id) on delete cascade not null,
  item_order integer not null,
  points integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(test_id, question_id)
);


-- Row Level Security (RLS)

alter table profiles enable row level security;
alter table books enable row level security;
alter table book_chunks enable row level security;
alter table book_entities enable row level security;
alter table book_themes enable row level security;
alter table question_bank enable row level security;
alter table tests enable row level security;
alter table test_items enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

create policy "Users can view own books." on books for select using (auth.uid() = user_id);
create policy "Users can insert own books." on books for insert with check (auth.uid() = user_id);
create policy "Users can update own books." on books for update using (auth.uid() = user_id);
create policy "Users can delete own books." on books for delete using (auth.uid() = user_id);

-- For related tables, policy checks the parent book owner
create policy "Users can view chunks of own books." on book_chunks for select using (exists (select 1 from books where books.id = book_chunks.book_id and books.user_id = auth.uid()));
create policy "Users can view entities of own books." on book_entities for select using (exists (select 1 from books where books.id = book_entities.book_id and books.user_id = auth.uid()));
create policy "Users can view themes of own books." on book_themes for select using (exists (select 1 from books where books.id = book_themes.book_id and books.user_id = auth.uid()));
create policy "Users can view questions of own books." on question_bank for select using (exists (select 1 from books where books.id = question_bank.book_id and books.user_id = auth.uid()));

-- Insert policies for background jobs (service role) typically bypass RLS
-- But for frontend inserts:
create policy "Users can insert questions for own books." on question_bank for insert with check (exists (select 1 from books where books.id = question_bank.book_id and books.user_id = auth.uid()));

create policy "Users can view own tests." on tests for select using (auth.uid() = user_id);
create policy "Users can insert own tests." on tests for insert with check (auth.uid() = user_id);
create policy "Users can update own tests." on tests for update using (auth.uid() = user_id);
create policy "Users can delete own tests." on tests for delete using (auth.uid() = user_id);

create policy "Users can view own test items." on test_items for select using (exists (select 1 from tests where tests.id = test_items.test_id and tests.user_id = auth.uid()));
create policy "Users can insert own test items." on test_items for insert with check (exists (select 1 from tests where tests.id = test_items.test_id and tests.user_id = auth.uid()));
create policy "Users can update own test items." on test_items for update using (exists (select 1 from tests where tests.id = test_items.test_id and tests.user_id = auth.uid()));
create policy "Users can delete own test items." on test_items for delete using (exists (select 1 from tests where tests.id = test_items.test_id and tests.user_id = auth.uid()));


-- Vector index for similarity search
create index on book_chunks using hnsw (embedding vector_cosine_ops);

-- Triggers for updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

create trigger update_books_updated_at before update on books for each row execute procedure update_updated_at_column();
create trigger update_tests_updated_at before update on tests for each row execute procedure update_updated_at_column();
